module.exports = {
  search: require('./search'),
  get: require('./get'),
  replies: require('./replies'),
  note: require('./note'),
  my: require('./my'),
  post: require('./post'),
  delete: require('./delete'),
  like: require('./like'),
  analyze: require('./analyze'),
  suggest: require('./suggest'),
  dashboard: require('./dashboard'),
  log: require('./log'),
  profile: require('./profile'),
  events: require('./events'),
  whois: require('./whois'),
  // v2 反馈闭环命令
  corpus: require('./corpus'),
  failures: require('./failures'),
  dedup: require('./dedup'),
};
