module.exports = {
  search: require('./search'),
  get: require('./get'),
  replies: require('./replies'),
  note: require('./note'),
  my: require('./my'),
  post: require('./post'),
  delete: require('./delete'),
  like: require('./like'),
  analyze: require('./analyze'),
  suggest: require('./suggest'),
  dashboard: require('./dashboard'),
  log: require('./log'),
  profile: require('./profile'),
};
